### ISSUE TITLE
Wrong link on npm package?

### ISSUE THREAD

**Issue by mellson** [alexfedoseev/re-debouncer#10]
Thanks for creating this, it makes it super easy to debounce in ReScript!

I just noticed that the npm package for [rescript-debounce-react](https://www.npmjs.com/package/rescript-debounce-react) contains dead links to homepage and repo.

It links to `https://github.com/shakacode/rescript-debounce-react#readme` which I guess should be `https://github.com/shakacode/rescript-debounce/tree/master/rescript-debounce-react`?

**Comment by zatchheems** [comment]
I'd also like to extend my thanks for this package. Just shy of a year later, the npm package still contains dead links.

**Comment by alex35mil** [comment]
Sorry folks, it's npm who does these dead links. Fixed.
