### ISSUE TITLE
How to use?

### ISSUE THREAD

**Issue by sebastienroussel** [alexfedoseev/re-debouncer#3]
Hi,

I'm trying to debounce a function call that filters an array of elements given an Input. 
I want the filtering to be done after 0.5 seconds after the user stopped inserting input.

My function is : 

```
let filterArray = (arrayToFilter, filterInput) =>
Belt.Array.keep(arrayToFilter, element => 
Js.String.includes(Js.String.toLowerCase(filterInput), Js.String.toLowerCase(element |> string_of_int)));

```

It works fine with no debouncing.

If I try : 
`let debouncedFilter = Debouncer.make(((array, input)) => filterArray(array, input));
`
I should be able to then use : 
`debouncedFilter((array, input));
`

But I get an error with unit : 
`This has type:
    array()
  But somewhere wanted:
    unit`

In the source I see : 
`fn : 'a => unit`

So can we only debounce functions wich return unit? How would I adapt my example to work?

**Comment by alex35mil** [comment]
@sebastienroussel I assume array of elements is stored in some state which can be updated. If it's stored in a state of react component, then you can dispatch actions which would trigger update of array in state and then re-render the UI tree. So to achieve what you're trying to do you need to perform filtering inside debounced function and then dispatch an action with the result:

```reason
Debouncer.make(((array, input)) => UpdateArray(filterArray(array, input))->dispatch);
```

If you use something other than react, the mechanism should be similar.

**Comment by alex35mil** [comment]
Feel free to re-open if you have other questions.
